### ISSUE TITLE
Unable to install 'antfu.auto-npx' extension because it is not compatible with the current version of VS Code (version 1.56.2).

### ISSUE THREAD

**Issue by HuanBaby1314** [antfu/vscode-auto-npx#1]
![image](https://user-images.githubusercontent.com/28698252/134792404-6425bb84-4079-4c4a-80e1-7182348e09dc.png)
不兼容呀！你的vscode版本是多少？
what's your vscode version?

**Comment by ch3cknull** [comment]
我用如下配置是没问题的

- Win10 20H2
- WSL2
- VS Code 1.60.2

手头没有苹果机器，不清楚是不是系统的问题了

**Comment by HuanBaby1314** [comment]
> 我用如下配置是没问题的
> 
> * Win10 20H2
> * WSL2
> * VS Code 1.60.2
> 
> 手头没有苹果机器，不清楚是不是系统的问题了

我先升个级看看，之前vs code升级后有问题一直用这个版本的

**Comment by HuanBaby1314** [comment]
> 版本: 1.60.2 (Universal)
提交: 7f6ab5485bbc008386c4386d08766667e155244e
日期: 2021-09-22T11:59:27.195Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.2.0

最新版安装无问题。
