### ISSUE TITLE
Feature Request - Add PowerShell Support

### ISSUE THREAD

**Issue by ch3cknull** [antfu/vscode-auto-npx#2]
Now `export` command **not support** in PowerShell 

PowerShell use this Command

```powershell
$env:Path = "$env:Path;$pwd\node_modules\.bin\"
```

Thanks!

**Comment by alexanderniebuhr** [comment]
You could also define this in VS Code Settings for all platforms.
```
"terminal.integrated.env.<PLATFORM>": {
  ...
}
```

For PowerShell my Setting looks for some month now is this:
@ch3cknull hope this helps you already
```
"terminal.integrated.env.windows": {
   "PATH": "${env:PATH};${workspaceRoot}/node_modules/.bin"
}
```

**Comment by ch3cknull** [comment]
> You could also define this in VS Code Settings for all platforms.
> 
> ```
> "terminal.integrated.env.<PLATFORM>": {
>   ...
> }
> ```
> 
> For PowerShell my Setting looks for some month now is this:
> @ch3cknull hope this helps you already
> 
> ```
> "terminal.integrated.env.windows": {
>    "PATH": "${env:PATH};${workspaceRoot}/node_modules/.bin"
> }
> ```

Thanks! It looks good!
